version: '3.8'

services:
  postgres-auth:
    image: postgres:latest
    container_name: postgres-auth
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/auth-service:/var/lib/postgresql/data
  
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    env_file:
      - ./auth-service/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres-auth

volumes:
  postgres-auth-data:
